/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControladoresVistas;

import Modelos.Circulo;
import Modelos.Cuadrado;
import Modelos.Imagen;
import java.awt.Color;
import java.util.Scanner;

/**
 *
 * @author pipet
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
//        Cuadrado cuadrado1= new Cuadrado(10, 10, Color.black, Color.red, 90);
//        Circulo circulo1=new Circulo(100, 10, Color.blue, Color.green, 70);
//        Imagen elHongo=new Imagen(10, 100, "src/Imagenes/hongo.png", 64, 64);
//        this.lienzo1.getFiguras().add(cuadrado1);
//        this.lienzo1.getFiguras().add(circulo1);
//        this.lienzo1.getFiguras().add(elHongo);

          //System.out.println("Ingrese la matriz del dibujo que desea realizar");
          
          
          //Scanner matrizDibujo = new Scanner(System.in);
          //0:blanco, 1:rojo, 2:negro, 3:naranja, 4:azul, 5:amarillo
          int matriz[][] = {{0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0},
                            {0,0,0,0,1,1,1,1,1,1,1,1,1,0,0,0},
                            {0,0,0,0,2,2,2,3,3,2,3,0,0,0,0,0},
                            {0,0,0,2,3,2,3,3,3,2,3,3,3,0,0,0},
                            {0,0,0,2,3,2,2,3,3,3,2,3,3,3,0,0},
                            {0,0,0,0,2,3,3,3,3,2,2,2,2,0,0,0},
                            {0,0,0,0,0,3,3,3,3,3,3,0,0,0,0,0},
                            {0,0,0,0,1,1,4,1,1,4,1,1,0,0,0,0},
                            {0,0,0,1,1,1,4,1,1,4,1,1,1,0,0,0},
                            {0,0,1,1,1,1,4,4,4,4,1,1,1,1,0,0},
                            {0,0,3,3,1,4,5,4,4,5,4,1,3,3,0,0},
                            {0,0,3,3,3,4,4,4,4,4,4,3,3,3,0,0},
                            {0,0,3,3,4,4,4,4,4,4,4,4,3,3,0,0},
                            {0,0,0,0,4,4,4,0,0,4,4,4,0,0,0,0},
                            {0,0,0,2,2,2,0,0,0,0,2,2,2,0,0,0},
                            {0,0,2,2,2,2,0,0,0,0,2,2,2,2,0,0}};
          pintar_dibujo(matriz);
    }
    
    
    public void pintar_dibujo(int matriz[][]){
        int x = 0;
        int y = 0;
        int c = 0;
        for (int i = 0; i < matriz.length; i++) {
            for (int j = matriz.length/2; j < matriz.length; j++) {
                if (matriz[i][j] == 0 ) {
                    Cuadrado nuevoCuadrado = new Cuadrado(x+y, c, Color.white, Color.white, 30);
                    this.lienzo2.getFiguras().add(nuevoCuadrado);
                }else if(matriz[i][j] == 1){
                    Cuadrado nuevoCuadrado = new Cuadrado(x+y, c, Color.red, Color.red, 30);
                    this.lienzo2.getFiguras().add(nuevoCuadrado);
                }else if(matriz[i][j] == 2){
                    Cuadrado nuevoCuadrado = new Cuadrado(x+y, c, Color.black, Color.black, 30);
                    this.lienzo2.getFiguras().add(nuevoCuadrado);
                }else if(matriz[i][j] == 3){
                    Cuadrado nuevoCuadrado = new Cuadrado(x+y, c, Color.orange, Color.orange, 30);
                    this.lienzo2.getFiguras().add(nuevoCuadrado);
                }
                else if(matriz[i][j] == 4){
                    Cuadrado nuevoCuadrado = new Cuadrado(x+y, c, Color.blue, Color.blue, 30);
                    this.lienzo2.getFiguras().add(nuevoCuadrado);
                }else if(matriz[i][j] == 5){
                    Cuadrado nuevoCuadrado = new Cuadrado(x+y, c, Color.yellow, Color.yellow, 30);
                    this.lienzo2.getFiguras().add(nuevoCuadrado);
                }
                y += 30;
            }
            x=0;
            y=0;
            c+=30;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo2 = new ControladoresVistas.Lienzo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lienzo2Layout = new javax.swing.GroupLayout(lienzo2);
        lienzo2.setLayout(lienzo2Layout);
        lienzo2Layout.setHorizontalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1075, Short.MAX_VALUE)
        );
        lienzo2Layout.setVerticalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lienzo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lienzo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ControladoresVistas.Lienzo lienzo2;
    // End of variables declaration//GEN-END:variables
}
